Compute an inversion of the matrix (Transpose)

In [26]:
import numpy as np
from numpy import transpose

In [27]:
#Matrix
matrix = np.array([[1, 0.2, 0.5],
                   [0.2, 1, 0.8],
                   [0.5, 0.8, 1]])

Compute an Inversion of the Matrix (Transpose)

In [28]:
transpose_matrix = np.transpose(matrix)
print("Transpose Matrix:\n", transpose_matrix)

Transpose Matrix:
 [[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


Compute the determinant of the Matrix if possible

In [29]:
determinant = np.linalg.det(matrix)
print("Determinant of the Matrix:", determinant)

Determinant of the Matrix: 0.2299999999999999


Decompose  the Matrix

In [30]:
# (c) Decompose the matrix
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [2.04100779 0.82188052 0.13711169]
Eigenvectors:
 [[-0.43721717 -0.85359707 -0.28321933]
 [-0.59931898  0.51133314 -0.61591816]
 [-0.67056536  0.09955128  0.73514055]]


Transform the Matrix 